name: CM Backport PR

on:
  push:
    branches:
      - master

jobs:
  backport:
    name: CM Backport PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Backport from master to stg
        id: cmb
        uses: cristiammercado/cm-backport-pr@1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pr-from-branch: master
          pr-to-branch: stg
          pr-title: "A PR title"
          pr-body: "The PR body."
          pr-fail-if-exists: false
          pr-update-if-exists: false
          maintainer-can-modify: true
          draft: false
          merge-pr-after-created: true
          merge-commit-title: "Merge commit title"
          merge-commit-body: "Merge commit message."
          merge-method: merge

      - name: Backport from master to dev
        id: cmb2
        uses: cristiammercado/cm-backport-pr@1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pr-from-branch: master
          pr-to-branch: dev
          pr-title: "A PR title"
          pr-body: "The PR body."
          pr-fail-if-exists: false
          pr-update-if-exists: false
          maintainer-can-modify: true
          draft: false
          merge-pr-after-created: true
          merge-commit-title: "Merge commit title"
          merge-commit-body: "Merge commit message."
          merge-method: merge
